web:
  port: ${PORT}

alerting:
  discord:
    webhook-url: "https://discord.com/api/webhooks/1511420350972297386/LaJi6dOQS0Qlez0DmgqA_ZSL_6bX-sMgYm1FCV3BOTVOCl2KcdpLR1P8XlsfeVRQ2Ytc"
    title: "🚨 ALARME"
    default-alert:
      enabled: true
      failure-threshold: 3
      success-threshold: 2
      send-on-resolved: true

  custom:
    url: "https://api-v2-684289935571.us-central1.run.app/internal/webhook/status"
    method: "POST"
    headers:
      Content-Type: "application/json"
      x-token: "CbJejNf6Fg3+IDgYUOZUZZDm/bFuOE280NZ+5Rect2Q="
    body: |
      {
        "event": "[ALERT_TRIGGERED_OR_RESOLVED]",
        "endpointId": "[ALERT_DESCRIPTION]"
      }
    default-alert:
      enabled: true
      failure-threshold: 2
      success-threshold: 1
      send-on-resolved: true

ui:
  title: "Pixie • Status do sistema"
  description: "Confira se o Pixie está funcionando como esperado."
  dashboard-heading: "Status do sistema"
  dashboard-subheading: "Confira se o Pixie está funcionando como esperado"
  header: "Pixie"
  dark-mode: false
  custom-css: |
    header {
      border: 0;
    }

.default-public-endpoint: &public_settings
  interval: 1m
  ui:
    hide-url: true
    hide-hostname: true
    hide-port: true
    hide-conditions: true
    hide-errors: true
  alerts:
    - type: discord
  conditions:
    - "[STATUS] < 400"

announcements:
  - timestamp: 2026-06-26T17:17:00Z
    type: outage
    message: "PIX temporariamente indisponível devido a um erro do Banco do Brasil. Estamos acompanhando a situação e iremos atualizar o status assim que o problema for resolvido."
    archived: true
  - timestamp: 2026-06-26T21:11:00Z
    type: operational
    message: "O Banco do Brasil solucionou o problema e o PIX está operando normalmente."

storage:
  type: postgres
  path: "${DATABASE_URL}"
  caching: true
  maximum-number-of-results: 44000
  maximum-number-of-events: 500

endpoints:
  - name: "Pagamentos via PIX"
    url: "https://api-v2-684289935571.us-central1.run.app/internal/health/pix"
    method: GET
    headers:
      x-token: "CbJejNf6Fg3+IDgYUOZUZZDm/bFuOE280NZ+5Rect2Q="
    <<: *public_settings
    interval: 3m
    alerts:
      - type: discord
        failure-threshold: 2
        success-threshold: 5
      - type: custom
        description: "pix"

  - name: "Pagamentos internacionais"
    url: "https://api-v2-684289935571.us-central1.run.app/internal/health/intl"
    method: GET
    headers:
      x-token: "CbJejNf6Fg3+IDgYUOZUZZDm/bFuOE280NZ+5Rect2Q="
    <<: *public_settings
    interval: 5m
    alerts:
      - type: discord
        failure-threshold: 2
        success-threshold: 5
      - type: custom
        description: "intl"

  - name: "IA generativa"
    url: "https://api-v2-684289935571.us-central1.run.app/internal/health/ai-voices"
    method: GET
    headers:
      x-token: "CbJejNf6Fg3+IDgYUOZUZZDm/bFuOE280NZ+5Rect2Q="
    <<: *public_settings

  - name: "API principal"
    url: "https://api.pixie.gg"
    method: GET
    <<: *public_settings

  - name: "Página principal"
    url: "https://pixie.gg"
    method: GET
    <<: *public_settings

  - name: "Painel do criador"
    url: "https://dashboard.pixie.gg"
    method: GET
    <<: *public_settings
