web:
  port: ${PORT}

ui:
  title: "Pixie • Status do sistema"
  description: "Confira se o Pixie está funcionando como esperado."
  dashboard-heading: "Status do sistema"
  dashboard-subheading: "Confira se o Pixie está funcionando como esperado."
  header: "Pixie"
  dark-mode: false
  custom-css: |
    header {
      border: 0;
    }

    footer {
      border: 0;
    }

    div#social {
      display: none;
    }

.default-public-endpoint: &public_settings
  interval: 1m
  ui:
    hide-url: true
    hide-hostname: true
    hide-port: true
    hide-conditions: true
    hide-errors: true

storage:
  type: postgres
  path: "${DATABASE_URL}"

endpoints:
  - name: "Pagamentos via PIX"
    url: "https://api-v2-684289935571.us-central1.run.app/internal/health/pix"
    method: GET
    headers:
      x-token: "CbJejNf6Fg3+IDgYUOZUZZDm/bFuOE280NZ+5Rect2Q="
    <<: *public_settings
    conditions:
      - "[STATUS] < 400"

  - name: "Pagamentos internacionais"
    url: "https://api-v2-684289935571.us-central1.run.app/internal/health/intl"
    method: GET
    headers:
      x-token: "CbJejNf6Fg3+IDgYUOZUZZDm/bFuOE280NZ+5Rect2Q="
    <<: *public_settings
    conditions:
      - "[STATUS] < 400"

  - name: "IA generativa"
    url: "https://api-v2-684289935571.us-central1.run.app/internal/health/ai-voices"
    method: GET
    headers:
      x-token: "CbJejNf6Fg3+IDgYUOZUZZDm/bFuOE280NZ+5Rect2Q="
    <<: *public_settings
    conditions:
      - "[STATUS] < 400"

  - name: "API principal"
    url: "https://api.pixie.gg"
    method: GET
    <<: *public_settings
    conditions:
      - "[STATUS] < 400"

  - name: "Página principal"
    url: "https://pixie.gg"
    method: GET
    <<: *public_settings
    conditions:
      - "[STATUS] < 400"

  - name: "Painel do criador"
    url: "https://dashboard.pixie.gg"
    method: GET
    <<: *public_settings
    conditions:
      - "[STATUS] < 400"
